import React from "react";
export const indexStocksNames = [
  {
    name: "NIFTY 50",
    symbol: "nifty",
  },
  { name: "NIFTY NEXT 50", symbol: "juniorNifty" },
  { name: "NIFTY MIDCAP 50", symbol: "niftyMidcap50" },
  { name: "NIFTY AUTO", symbol: "cnxAuto" },
  { name: "NIFTY BANK", symbol: "bankNifty" },
  { name: "NIFTY ENERGY", symbol: "cnxEnergy" },
  { name: "NIFTY FIN SERVICE", symbol: "cnxFinance" },
  { name: "NIFTY FMCG", symbol: "cnxFMCG" },
  { name: "NIFTY IT", symbol: "cnxit" },
  { name: "NIFTY MEDIA", symbol: "cnxMedia" },
  { name: "NIFTY METAL", symbol: "cnxMetal" },
  { name: "NIFTY PHARMA", symbol: "cnxPharma" },
  { name: "NIFTY PSU BANK", symbol: "cnxPSU" },
  { name: "NIFTY REALTY", symbol: "cnxRealty" },
  { name: "NIFTY PVT BANK", symbol: "niftyPvtBank" },
  { name: "NIFTY COMMODITIES", symbol: "cnxCommodities" },
  { name: "NIFTY CONSUMPTION", symbol: "cnxConsumption" },
  { name: "NIFTY CPSE", symbol: "cpse" },
  { name: "NIFTY INFRA", symbol: "cnxInfra" },
  { name: "NIFTY MNC", symbol: "cnxMNC" },
  { name: "NIFTY GROWSECT 15", symbol: "ni15" },
  { name: "NIFTY PSE", symbol: "cnxPSE" },
  { name: "NIFTY SERV SECTOR", symbol: "cnxService" },
  { name: "NIFTY100 LIQ 15", symbol: "nseliquid" },
  { name: "NIFTY MID LIQ 15", symbol: "niftyMidcapLiq15" },
  { name: "NIFTY DIV OPPS 50", symbol: "cnxDividendOppt" },
  { name: "NIFTY50 VALUE 20", symbol: "nv20" },
  { name: "NIFTY QUALITY 30", symbol: "niftyQuality30" },
  { name: "NIFTY50 EQL WGT", symbol: "nifty50EqualWeight" },
  { name: "NIFTY100 EQL WGT", symbol: "nifty100EqualWeight" },
  { name: "NIFTY100 LOWVOL30", symbol: "nifty100LowVolatility30" },
  { name: "NIFTY ALPHA 50", symbol: "niftyAlpha50" },
];
